name: Install dependencies via apt-get
runs:
  using: composite
  steps:
  - name: SDL2
    uses: awalsh128/cache-apt-pkgs-action@latest
    with:
      packages: libsdl2-dev
      version: 2.0
  - name: SDL3
    uses: awalsh128/cache-apt-pkgs-action@latest
    with:
      packages: |
        build-essential git make
        pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev 
        libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev 
        libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev 
        libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev 
        libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev
        libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev
        libharfbuzz-dev
      version: 3.0